#!/bin/bash
export MISE_RUBY_SETUP_SHIMS=1

if [ "$1" = "--version" ]; then
  echo "1.0.0"
  exit 0
fi

nohup "$HOME/.local/bin/Cursor-3.6.31-x86_64.AppImage" --enable-features=UseOzonePlatform --ozone-platform=wayland "$@" >/dev/null 2>&1 &
