export CONFIG_PATH=$HOME/.dotfiles

# if system is mac load mac specific zshrc
if [[ "$OSTYPE" == "darwin"* ]]; then
  source "$CONFIG_PATH/zsh/zshrc.mac"
fi

# if system is linux load linux specific zshrc
if [[ "$OSTYPE" == "linux-gnu"* ]]; then
  source "$CONFIG_PATH/zsh/zshrc.linux"
fi

# Load aliases
source "$CONFIG_PATH/zsh/zshrc.alias"

# opencode
export PATH=/home/fran/.opencode/bin:$PATH

# bun completions
[ -s "/home/fran/.bun/_bun" ] && source "/home/fran/.bun/_bun"

# bun
export BUN_INSTALL="$HOME/.bun"
export PATH="$BUN_INSTALL/bin:$PATH"

# pnpm
export PNPM_HOME="/home/fran/.local/share/pnpm"
case ":$PATH:" in
  *":$PNPM_HOME/bin:"*) ;;
  *) export PATH="$PNPM_HOME/bin:$PATH" ;;
esac
# pnpm end


# Added by Antigravity CLI installer
export PATH="/home/fran/.local/bin:$PATH"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

# Token Savior
export TS_BASH_COMPACT=1
export TS_BASH_REWRITE=1
export TOKEN_SAVIOR_PROFILE=optimized
